#!/bin/bash

main () {
cwd=$(pwd)
depth=0
echo "Indexing $(pwd)"
header
directories
footer
find . -mindepth 2 -type d -path '*/\.*' -prune -o -type d -print | sed -e 's/.//' -e 's/\///' | sort | while IFS= read -r cdir
  do
    cd "${cdir}"
    title=$(awk -F / '{print $NF}' <<< ${cdir} | sed 's/-/ /g')
    parent=$(awk -F / '{print $(NF-1)}' <<< ${cdir} | sed 's/-/ /g')
    css=$(sed -e 's/\/[^\/]*/\/../g' -e 's/.\///' <<< ${cdir})
    depth=$(awk -F / '{print NF}' <<< ${cdir})
    dots=$(printf "%0.s../" $(seq $depth))
    files=$(find . -maxdepth 1 -type f ! -iname index.html)
    echo "Indexing $(pwd)"
    header
    tabs
    directories
    footer
    cd "$cwd"
done
}

header () {
    echo '<!DOCTYPE html>' > index.html
    echo '<html lang="en">' >> index.html
    echo '  <head>' >> index.html
    if [[ $depth = 0 ]]
      then
        echo "    <title>tabs</title>" >> index.html
      else
        echo "    <title>${title}</title>" >> index.html
    fi
    echo '    <meta charset="UTF-8" />' >> index.html
    echo '    <meta name="viewport" content="width=device-width, initial-scale=1.0">' >> index.html
    if [[ $depth = 0 ]]
      then  
        echo "    <link href=\".css/main.css\" rel=\"stylesheet\" type=\"text/css\" />" >> index.html
      else
        echo "    <link href=\"${dots}.css/main.css\" rel=\"stylesheet\" type=\"text/css\" />" >> index.html
    fi
    echo '  </head>' >> index.html
    echo '  <body>' >> index.html
    echo '    <div id="page">' >> index.html
    echo '    <header>' >> index.html
    breadcrumbs
    echo '    </header>' >> index.html
    echo '    <div id="content">' >> index.html
}

breadcrumbs () {
    if [[ $depth != 0 ]]
      then
        echo '      <ul class="breadcrumb">' >> index.html
        echo "        <li class=\"crumb\">// </li>" >> index.html
        echo "        <li class=\"crumb\"><a href=\"../..\">tabs</a></li>" >> index.html
        echo "        <li class=\"crumb\"> // </li>" >> index.html
        echo "        <li class=\"crumb\">${parent}</li>" >> index.html
        echo "        <li class=\"crumb\"> // </li>" >> index.html
        echo "        <li class=\"crumb title\">${title}</li>" >> index.html
        echo '      </ul>' >> index.html
    fi
}

directories () {
    find . -maxdepth 1 -type d ! -iname ".*" | sed -e 's/.//' -e 's/\///' | sort | while IFS= read -r dir
      do
	artist=$(echo "${dir}" | sed 's/-/ /g')
        echo '      <div class="list">' >> index.html
        echo "        <a><h2>${artist}</h2></a>" >> index.html
        echo '        <ul>' >> index.html
        find "$dir" -mindepth 1 -maxdepth 1 -type d ! -iname ".*" | sort | while IFS= read -r subdir
          do
            song=$(basename "${subdir}" | sed 's/-/ /g')
            echo "          <li><a href=\"${subdir}\">${song}</a></li>" >> index.html
        done
        echo '        </ul>' >> index.html
        echo '      </div>' >> index.html
    done
}

tabs () {
    if [[ $files ]]
      then
        for tab in *.tab
          do
            echo "        <!--#include file=\"${tab}\" -->" >> index.html
        done
    fi
}

footer () {
    depth=$(awk -F / '{print NF}' <<< ${cdir})
    echo '      </div>' >> index.html
    echo '    <footer>' >> index.html
    breadcrumbs
    echo '    </footer>' >> index.html
    echo '    </div>' >> index.html
    echo '  </body>' >> index.html
    echo '</html>' >> index.html
}

main
