#!/bin/bash

main () {
cwd=$(pwd)
depth=0
echo "Indexing $(pwd)"
header > index.html
{
  directories
  footer
} >> index.html
while IFS= read -r cdir
  do
    cd "${cdir}" || return
    title=$(awk -F / '{print $NF}' <<< "${cdir//-/ }")
    parent=$(awk -F / '{print $(NF-1)}' <<< "${cdir//-/ }")
    depth=$(awk -F / '{print NF}' <<< "${cdir}")
    dots=$(printf "%0.s../" $(seq "$depth"))
    files=$(find . -maxdepth 1 -type f ! -iname index.html)
    echo "Indexing $(pwd)"
    header > index.html
    {
      tabs
      directories
      footer
    } >> index.html
    cd "$cwd" || return
done < <(find . -mindepth 2 -type d -path '*/\.*' -prune -o -type d -print | sed -e 's/.//' -e 's/\///' | sort)
}

header () {
    echo '<!DOCTYPE html>'
    echo '<html lang="en">'
    echo '  <head>'
    if [[ $depth = 0 ]]
      then
        echo "    <title>tabs</title>"
      else
        echo "    <title>${title}</title>"
    fi
    echo '    <meta charset="UTF-8" />'
    echo '    <meta name="viewport" content="width=device-width, initial-scale=1.0">'
    if [[ $depth = 0 ]]
      then  
        echo "    <link href=\".css/main.css\" rel=\"stylesheet\" type=\"text/css\" />"
      else
        echo "    <link href=\"${dots}.css/main.css\" rel=\"stylesheet\" type=\"text/css\" />"
    fi
    echo '  </head>'
    echo '  <body>'
    echo '    <header>'
    breadcrumbs
    echo '    </header>'
    echo '    <main>'
}

breadcrumbs () {
    if [[ $depth != 0 ]]
      then
        echo '      <ul class="breadcrumb">'
        echo "        <li class=\"crumb\">// </li>"
        echo "        <li class=\"crumb\"><a href=\"../..\">tabs</a></li>"
        echo "        <li class=\"crumb\"> // </li>"
        echo "        <li class=\"crumb\">${parent}</li>"
        echo "        <li class=\"crumb\"> // </li>"
        echo "        <li class=\"crumb title\">${title}</li>"
        echo '      </ul>'
    fi
}

directories () {
    while IFS= read -r dir
      do
	artist="${dir//-/ }"
        echo '      <ul class="list">'
        echo "        <li><h2>${artist}</h2></li>"
        find "$dir" -mindepth 1 -maxdepth 1 -type d ! -iname ".*" | sort | while IFS= read -r subdir
          do
            song=$(basename "${subdir}" | sed 's/-/ /g')
            echo "          <li><a href=\"${subdir}/\">${song}</a></li>"
        done
        echo '      </ul>'
    done < <(find . -maxdepth 1 -type d ! -iname ".*" | sed -e 's/.//' -e 's/\///' | sort)
}

tabs () {
    if [[ $files ]]
      then
        for tab in *.tab
          do
            cat "${tab}"
        done
    fi
}

footer () {
    depth=$(awk -F / '{print NF}' <<< "${cdir}")
    echo '    </main>'
    echo '    <footer>'
    breadcrumbs
    echo '    </footer>'
    echo '  </body>'
    echo '</html>'
}

main
